name: ultrabottrader
description: A production-ready autonomous cryptocurrency trading bot.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.0
  http: ^1.1.0
  riverpod: ^2.4.5
  fl_chart: ^0.65.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
