name: Android CI

on: [push]

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x' # Use a specific Flutter version, e.g., '3.19.x' or '3.x' for latest stable
        channel: 'stable'

    - name: Get Flutter dependencies
      run: flutter pub get
      working-directory: trading_bot_app

    - name: Build Android APK
      run: flutter build apk --release
      working-directory: trading_bot_app

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: trading_bot_app/build/app/outputs/flutter-apk/app-release.apk
